### PR TITLE
Formatted the repo to support pip and also made changes to follow standard PEP rules.

### PR DESCRIPTION
**Pull request by ArjixGamer**
sorry for weird commit history, i deleted the repo to upload my local one, since i dont use git cli its messed up.

### CODE REVIEW

**Comment by ArjixGamer** [comment]
I think this is an interesting project, and I am interested in becoming a regular contributor.
My discord is: Arjix#7453

**Comment by ArjixGamer** [comment]
If you want instructions on how to publish to pip you can always message me on discord!

**Comment by thesadru** [comment]
I'm so sorry I haven't replied earlier, it's been a while since I checked this repo. The changes don't seem like they will break anything, however it will require an `__init__.py` file, so I'll merge it when I have time to make some small changes and make it actually properly usable.

**Comment by ArjixGamer** [comment]
oh yeah, i did not properly test it, should have fixed it now

**Comment by ArjixGamer** [comment]
also i might be using the program incorrectly, but i tried this command 
``animethemes-dl ArjixGamer --al --audio-folder H:/Music --ascii --coverart --local-convert --try-both`` 
and it outputs this:
```
[progress] initializing program
[get] getting data from anilist.coTraceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\animethemes-dl.exe\__main__.py", line 4, in <module>
  File "c:\python38\lib\site-packages\animethemes_dl\main.py", line 165, in <module>
    batch_download(
  File "c:\python38\lib\site-packages\animethemes_dl\downloader.py", line 437, in batch_download
    download_data = get_download_data(username, statuses, anilist, extra_ids)
  File "c:\python38\lib\site-packages\animethemes_dl\downloader.py", line 148, in get_download_data
    data = get_proper(username, anilist, extra_ids, **mal_args)
  File "c:\python38\lib\site-packages\animethemes_dl\animethemes.py", line 211, in get_proper
    list_data = al_get(username)
  File "c:\python38\lib\site-packages\animethemes_dl\animethemes.py", line 198, in al_get
    return sort_al(r.json())
  File "c:\python38\lib\site-packages\animethemes_dl\animethemes.py", line 167, in sort_al
    status = {
KeyError: 'REPEATING'
```

**Comment by thesadru** [comment]
yeah, I'm guessing I know what the problem is. Since AnilIst uses REPEATING which is basically a glorified WATCHING, I'll just have to implement an edge case

**Comment by thesadru** [comment]
Weird commit history, wrong entry points, cannot properly check if it functions. Changes according to PEP are minor and more annoying than they should be, no actual bug was fixed.

**Pull request closed without merging**
